# Generated by Django 3.2 on 2022-06-06 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserName',
        ),
    ]
